version: '2'

services:
    userworks:
        image: 'docker-spring-boot-postgres:latest'
        build:
            dockerfile: Dockerfile
            context: .
        container_name: userworks
        depends_on:
            - db
            - cache
        ports:
            - "8080:8080"
        networks:
            - webnet
    cache:
        image: 'redis'
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        networks:
            - webnet
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        volumes:
            - ./database/data:/var/lib/userworks
        expose:
            - 5433
        environment:
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
        networks:
            - webnet
networks:
    webnet: